# Generated by Django 4.0.3 on 2022-04-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mark_as_sold',
            field=models.BooleanField(default=False),
        ),
    ]
